Database:
    Host: 127.0.0.1:27017
    Name: {DATABASE_NAME}

Mongo:
    Services:
        Webiny:
            Class: \Webiny\Component\Mongo\Mongo
            Arguments:
                Uri: 127.0.0.1:27017
                UriOptions:
                    database: {DATABASE_NAME}
    Driver: \Webiny\Component\Mongo\Bridge\MongoDb

Entity:
    Database: Webiny